### ISSUE TITLE
Index out of range when actor tries to find drop off

### ISSUE THREAD

**Issue by bkinnear** [switchboy/IsoRTS#36]
Vector index out of range error on line 1767. Worker's `buildingId` is -1

1. Set workers to gather resources with just Town Center
2. Wait for workers to try to return to drop off

![image](https://user-images.githubusercontent.com/42901829/135364723-4c45583e-687a-474f-a12d-218c62569e60.png)

**Comment by switchboy** [comment]
this->buildingId initiation was recently changed to -1. That is why this bug never came to light earlier. It is fixed now
